"""added needed models and removed unnecessary ones"

Revision ID: ed47f8b371ce
Revises: b58dc8dec546
Create Date: 2025-06-26 19:07:00.389968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed47f8b371ce'
down_revision = 'b58dc8dec546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index('ix_reviews_id')

    op.drop_table('reviews')
    op.drop_table('request_quote')
    op.drop_table('fleet_guides')
    op.drop_table('destinations')
    op.drop_table('our_company')
    op.drop_table('media')
    op.drop_table('contacts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('heroTitle', sa.VARCHAR(length=200), nullable=True),
    sa.Column('heroSubtitle', sa.VARCHAR(length=200), nullable=True),
    sa.Column('heroImage', sa.TEXT(), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('locationTitle', sa.VARCHAR(length=100), nullable=True),
    sa.Column('locationAddress', sa.TEXT(), nullable=True),
    sa.Column('locationTitle2', sa.VARCHAR(length=100), nullable=True),
    sa.Column('locationAddress2', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('heroTitle', sa.VARCHAR(length=200), nullable=True),
    sa.Column('heroSubtitle', sa.VARCHAR(length=200), nullable=True),
    sa.Column('heroImage', sa.TEXT(), nullable=True),
    sa.Column('photosHeading', sa.VARCHAR(length=200), nullable=True),
    sa.Column('photos', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('our_company',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('heroTitle', sa.VARCHAR(length=200), nullable=True),
    sa.Column('heroSubtitle', sa.VARCHAR(length=200), nullable=True),
    sa.Column('heroImage', sa.TEXT(), nullable=True),
    sa.Column('whoWeAre', sa.TEXT(), nullable=True),
    sa.Column('whyChooseUs', sa.TEXT(), nullable=True),
    sa.Column('reviewsIntro', sa.VARCHAR(length=200), nullable=True),
    sa.Column('reviews', sa.TEXT(), nullable=True),
    sa.Column('accreditationsTitle', sa.VARCHAR(length=200), nullable=True),
    sa.Column('accreditationsLogos', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('destinations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('image', sa.TEXT(), nullable=False),
    sa.Column('intro_text', sa.TEXT(), nullable=True),
    sa.Column('slug', sa.VARCHAR(length=100), nullable=False),
    sa.Column('accreditationsTitle', sa.VARCHAR(length=100), nullable=True),
    sa.Column('accreditationsLogos', sa.TEXT(), nullable=True),
    sa.Column('whyChooseUs', sa.TEXT(), nullable=True),
    sa.Column('reviewsIntro', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('fleet_guides',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('heroTitle', sa.VARCHAR(length=200), nullable=True),
    sa.Column('heroSubtitle', sa.VARCHAR(length=200), nullable=True),
    sa.Column('heroImage', sa.TEXT(), nullable=True),
    sa.Column('operatorsTitle', sa.VARCHAR(length=200), nullable=True),
    sa.Column('operatorsContent', sa.TEXT(), nullable=True),
    sa.Column('staffTitle', sa.VARCHAR(length=200), nullable=True),
    sa.Column('staffMembers', sa.TEXT(), nullable=True),
    sa.Column('privateTourGuideTitle', sa.VARCHAR(length=200), nullable=True),
    sa.Column('privateTourGuideText', sa.TEXT(), nullable=True),
    sa.Column('faqTitle', sa.VARCHAR(length=200), nullable=True),
    sa.Column('faqs', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_quote',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('heroTitle', sa.VARCHAR(length=200), nullable=True),
    sa.Column('heroSubtitle', sa.VARCHAR(length=200), nullable=True),
    sa.Column('heroImage', sa.TEXT(), nullable=True),
    sa.Column('formFields', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('author', sa.VARCHAR(length=100), nullable=False),
    sa.Column('rating', sa.INTEGER(), nullable=False),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.Column('destination_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index('ix_reviews_id', ['id'], unique=False)

    # ### end Alembic commands ###
